### ISSUE TITLE
Failling while generating the compute node VM

### ISSUE THREAD

**Issue by felixveysseyre** [Kitware/HPCCloud-deploy#103]
Hello,

I am trying to generate the VM containing the compute node.

In order to do that, I have executed the following commands:
```
cd compute
vagrant up
```

It run for a few minutes and I got the following error:
```
TASK [paraview : Install Python modules to allow SSL cert validation when download ParaView] ***
task path: /Users/felixveysseyre/Projects/XXXX/HPCCD/demo/roles/paraview/tasks/main.yml:14
failed: [hpccloud-compute-node-vm] (item=ndg-httpsclient) => {"failed": true, "item": "ndg-httpsclient", "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."}
failed: [hpccloud-compute-node-vm] (item=pyasn1) => {"failed": true, "item": "pyasn1", "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."}
	to retry, use: --limit @/Users/felixveysseyre/Projects/XXXX/HPCCD/demo/compute.retry

PLAY RECAP *********************************************************************
hpccloud-compute-node-vm   : ok=12   changed=8    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I am using:
- The latest version of HPCCloud-deploy: a30779b6232271c16e8064d20a03bd77e3d4ad0e
- MacOS: 10.11.2 (15C50)
- VirtualBox: 5.1.22 r115126 (Qt5.6.2)

Thanks for you help !

**Comment by cjh1** [comment]
@felixveysseyre This should fix the issue you are seeing #104

**Comment by felixveysseyre** [comment]
@cjh1 thank !

Do you have any idea when your PR will be merged ?

**Comment by cjh1** [comment]
Now!

**Comment by felixveysseyre** [comment]
Thank @cjh1, it seems to work now :)

However the download of ParaView `paraview : Download ParaView`is extremely slow.
Playrole is stuck at this point for more than an hour.

Do you have any idea ?

**Comment by cjh1** [comment]
@felixveysseyre It will be downloading the ParaView binary, so it is likely to be slow.
