### ISSUE TITLE
Error while executing demo simulation

### ISSUE THREAD

**Issue by felixveysseyre** [Kitware/HPCCloud-deploy#107]
I have successfuly generated both the compute node VM and the main VM.

I tried to create a OpenFoam simulation just to see if everything was running correctly.
Before creating the simulation, I have created a new cluster following the instructions found [here](https://github.com/Kitware/HPCCloud-deploy/tree/master/compute).

When I try to run the simulation from the `Simulation` tab, I go the following message in the `openfoam_run` section:

> [15:00:54.348] ERROR: makedirs() got an unexpected keyword argument 'ignore_failure'
>   File "/opt/hpccloud/cumulus/cumulus/tasks/job.py", line 280, in submit_job
>     conn.makedirs(job_dir, ignore_failure=True)
> TypeError: makedirs() got an unexpected keyword argument 'ignore_failure'

Let me know if have to do something special to run an `openfoam` simulation.
Maybe I should have created this issue on `HPCCloud` repo rather than the `HPCCloud-deploy`. Let me know.

Thanks

**Comment by cjh1** [comment]
@felixveysseyre So I only just got to this, last week was pretty busy, this should be resolved by Kitware/cumulus#329

**Comment by felixveysseyre** [comment]
Thanks @cjh1, it seemed to have fixed the issue !
