### ISSUE TITLE
Cluster authentication failed 

### ISSUE THREAD

**Issue by felixveysseyre** [Kitware/HPCCloud-deploy#109]
Hello,

I am trying to run a _OpenFoam_ simulation through HPCCloud using the compute node provided.

I have built _HPCCloud_ VM and the _ComputeNode_ VM as well.
I have added the ComputeNode cluster into HPCCloud instance using the `Preferences/Cluster` URL and following the instructions provided [here](https://github.com/Kitware/HPCCloud-deploy/tree/master/compute).

After adding the SSH key generated into the `authorized_key` file of the _ComputeNode_, I clicked the _Test_ button and everything seemed fine.

However, I am not able to run any simulation on this cluster since there is an issue with the authentication. Going to the `Preferences/Status` URL, and _Traditional Clusters_ section, I got the following error:

> [13:25:28.049] ERROR: Authentication failed.
>   File "/opt/hpccloud/cumulus/cumulus/tasks/cluster.py", line 173, in test_connection
>     with get_connection(girder_token, cluster) as conn:
>   File "/opt/hpccloud/cumulus/cumulus/transport/ssh.py", line 77, in __enter__
>     username=username, pkey=private_key)
>   File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 367, in connect
>     look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
>   File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 584, in _auth
>     raise saved_exception
> AuthenticationException: Authentication failed.

I do not know if it is a configuration issue or a bug.
Could you help me investigate on this ?

Thanks

**Comment by cjh1** [comment]
After you recreate the HPCCloud vm yesterday did you create a new cluster and add the new ssh key?

**Comment by felixveysseyre** [comment]
Yes, I rebuilt both VM from scratch

**Comment by cjh1** [comment]
@jourdain Have you using this setup recently?

**Comment by jourdain** [comment]
No but I will today... ;-)

**Comment by felixveysseyre** [comment]
Rebuilding the VMs today, I did not get the error.

I should have messed up somehow :)

**Comment by cjh1** [comment]
A mystery!
