### ISSUE TITLE
400 Client Error: Bad Request error in upload_ouput step

### ISSUE THREAD

**Issue by felixveysseyre** [Kitware/HPCCloud-deploy#110]
Hello,

Using latest master of _HPCCloud-deploy_ repository, I built the main and the compute VMs.

I created a project and a OpenFoam simulation. It seemed to run fine but I got the following error in the _upload_output_ step:

> File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/opt/hpccloud/cumulus/cumulus/taskflow/__init__.py", line 117, in wrapped
>     return func(celery_task, *args, **kwargs)
>   File "/opt/hpccloud/hpccloud/server/taskflows/hpccloud/taskflow/openfoam/tutorial.py", line 201, in upload_output
>     girder_token=task.taskflow.girder_token)
>   File "/opt/hpccloud/cumulus/cumulus/tasks/job.py", line 774, in upload_job_output_to_folder
>     assetstore_id = get_assetstore_id(girder_token, cluster)
>   File "/opt/hpccloud/cumulus/cumulus/transport/files/__init__.py", line 54, in get_assetstore_id
>     check_status(r)
>   File "/opt/hpccloud/cumulus/cumulus/common/__init__.py", line 32, in check_status
>     request.raise_for_status()
>   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 844, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> HTTPError: 400 Client Error: Bad Request for url: http://hydra.kitware.com:8080/api/v1/sftp_assetstores

Seems like a Girder API issue.

Thanks for your help !

**Comment by cjh1** [comment]
Can you send me the contents of /var/log/celery/command.log from the main VM?

**Comment by felixveysseyre** [comment]
Sure !

> [2017-11-16 17:02:32,439: INFO/MainProcess] Connected to amqp://guest:**@127.0.0.1:5672//
> [2017-11-16 17:02:32,452: INFO/MainProcess] mingle: searching for neighbors
> [2017-11-16 17:02:33,468: INFO/MainProcess] mingle: all alone
> [2017-11-16 17:02:33,496: WARNING/MainProcess] command@vagrant-ubuntu-trusty-64 ready.
> [2017-11-16 17:13:11,077: INFO/MainProcess] Received task: cumulus.ssh.tasks.key.generate_key_pair[0e1f9aa1-67c5-4166-8a1a-f606274e4adf]
> [2017-11-16 17:13:11,793: INFO/Worker-4] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:13:11,875: INFO/MainProcess] Task cumulus.ssh.tasks.key.generate_key_pair[0e1f9aa1-67c5-4166-8a1a-f606274e4adf] succeeded in 0.796767293s: None
> [2017-11-16 17:16:19,529: INFO/MainProcess] Received task: cumulus.tasks.cluster.test_connection[9f8aa743-4a5f-4a8b-9887-0289085dd104]
> [2017-11-16 17:16:19,536: INFO/Worker-2] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:16:19,613: INFO/Worker-2] Connected (version 2.0, client OpenSSH_6.6.1p1)
> [2017-11-16 17:16:19,666: WARNING/Worker-2] /usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
>   self._cipher = factory.new(key, *args, **kwargs)
> [2017-11-16 17:16:19,793: INFO/Worker-2] Authentication (publickey) successful!
> [2017-11-16 17:16:20,077: INFO/Worker-2] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:16:20,149: INFO/MainProcess] Task cumulus.tasks.cluster.test_connection[9f8aa743-4a5f-4a8b-9887-0289085dd104] succeeded in 0.619154166s: None
> [2017-11-16 17:17:58,016: INFO/MainProcess] Received task: cumulus.taskflow.cluster.setup_cluster[a68e1a13-c206-4824-a701-8c76bc8af862]
> [2017-11-16 17:17:58,021: INFO/Worker-1] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,069: INFO/Worker-1] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,116: INFO/Worker-1] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,114: INFO/Worker-1] We are using an existing cluster: ComputeVM
> [2017-11-16 17:17:58,267: INFO/Worker-1] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,327: INFO/MainProcess] Received task: hpccloud.taskflow.openfoam.tutorial.create_openfoam_job[2e8315b5-affa-4863-bc03-866801ce18e1]
> [2017-11-16 17:17:58,336: INFO/Worker-1] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,336: INFO/Worker-6] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,365: INFO/Worker-1] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,385: INFO/Worker-6] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,398: INFO/Worker-6] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,399: INFO/MainProcess] Task cumulus.taskflow.cluster.setup_cluster[a68e1a13-c206-4824-a701-8c76bc8af862] succeeded in 0.383074895s: None
> [2017-11-16 17:17:58,409: INFO/Worker-6] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,408: INFO/Worker-6] Creating OpenFoam job.
> [2017-11-16 17:17:58,419: INFO/Worker-6] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,434: INFO/Worker-6] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,432: INFO/Worker-6] OpenFOAM job created: 5a0dc8460640fd5788708946
> [2017-11-16 17:17:58,444: INFO/Worker-6] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,442: INFO/Worker-6] OpenFOAM job created.
> [2017-11-16 17:17:58,460: INFO/Worker-6] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,505: INFO/Worker-6] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,518: INFO/Worker-6] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,545: INFO/MainProcess] Received task: hpccloud.taskflow.openfoam.tutorial.submit_open_foam_job[e862d826-46af-4462-8de2-a345ed87c645]
> [2017-11-16 17:17:58,550: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,563: INFO/Worker-6] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,570: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,575: INFO/Worker-6] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,581: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:58,595: INFO/MainProcess] Task hpccloud.taskflow.openfoam.tutorial.create_openfoam_job[2e8315b5-affa-4863-bc03-866801ce18e1] succeeded in 0.266725674s: None
> [2017-11-16 17:17:58,580: INFO/Worker-3] Uploading input files to cluster.
> [2017-11-16 17:17:58,657: INFO/Worker-3] Connected (version 2.0, client OpenSSH_6.6.1p1)
> [2017-11-16 17:17:58,706: WARNING/Worker-3] /usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
>   self._cipher = factory.new(key, *args, **kwargs)
> [2017-11-16 17:17:58,824: INFO/Worker-3] Authentication (publickey) successful!
> [2017-11-16 17:17:59,112: INFO/Worker-3] [chan 0] Opened sftp connection (server version 3)
> [2017-11-16 17:17:59,173: INFO/Worker-3] [chan 0] sftp session closed.
> [2017-11-16 17:17:59,175: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:59,204: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:59,232: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:59,283: INFO/Worker-3] [chan 1] Opened sftp connection (server version 3)
> [2017-11-16 17:17:59,296: INFO/Worker-3] [chan 1] sftp session closed.
> [2017-11-16 17:17:59,301: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:59,409: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:59,408: INFO/Worker-3] Uploading complete.
> [2017-11-16 17:17:59,428: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:59,427: INFO/Worker-3] Submitting job to cluster.
> [2017-11-16 17:17:59,465: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:17:59,521: INFO/Worker-3] Connected (version 2.0, client OpenSSH_6.6.1p1)
> [2017-11-16 17:17:59,693: INFO/Worker-3] Authentication (publickey) successful!
> [2017-11-16 17:17:59,992: INFO/Worker-3] [chan 1] Opened sftp connection (server version 3)
> [2017-11-16 17:18:00,006: INFO/Worker-3] [chan 1] sftp session closed.
> [2017-11-16 17:18:00,078: INFO/Worker-3] [chan 2] Opened sftp connection (server version 3)
> [2017-11-16 17:18:00,082: INFO/Worker-3] [chan 2] sftp session closed.
> [2017-11-16 17:18:00,084: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:00,083: INFO/Worker-3] We have 1 slots available
> [2017-11-16 17:18:00,166: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:00,282: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:00,313: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:00,347: INFO/MainProcess] Received task: hpccloud.taskflow.openfoam.tutorial.monitor_open_foam_job[73d6d7d7-10ad-428a-bb79-3e0b17dc4be5]
> [2017-11-16 17:18:00,356: INFO/Worker-5] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:00,385: INFO/Worker-5] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:00,387: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:00,407: INFO/Worker-5] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:00,412: INFO/Worker-3] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:00,405: INFO/Worker-5] Monitoring job on cluster.
> [2017-11-16 17:18:00,431: INFO/Worker-5] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:00,434: INFO/MainProcess] Task hpccloud.taskflow.openfoam.tutorial.submit_open_foam_job[e862d826-46af-4462-8de2-a345ed87c645] succeeded in 1.888147524s: None
> [2017-11-16 17:18:00,469: INFO/Worker-5] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:00,489: INFO/Worker-5] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:00,508: INFO/MainProcess] Task hpccloud.taskflow.openfoam.tutorial.monitor_open_foam_job[73d6d7d7-10ad-428a-bb79-3e0b17dc4be5] succeeded in 0.159956317s: None
> [2017-11-16 17:18:08,755: INFO/MainProcess] Received task: cumulus.tasks.job.upload_job_output[b75a0456-92dc-472f-a6f3-d62a8f6606fb]
> [2017-11-16 17:18:08,757: INFO/Worker-4] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:08,800: INFO/Worker-4] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:08,800: INFO/Worker-4] Uploading output for "openfoam_run"
> [2017-11-16 17:18:08,848: INFO/Worker-4] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:08,864: INFO/MainProcess] Received task: hpccloud.taskflow.openfoam.tutorial.upload_output[235e1605-2fc8-4216-8e5e-38c52e24b266]
> [2017-11-16 17:18:08,867: INFO/Worker-2] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:08,869: INFO/Worker-4] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:08,897: INFO/Worker-2] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:08,913: INFO/Worker-2] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:08,937: INFO/Worker-2] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:08,936: INFO/Worker-2] Uploading results from cluster
> [2017-11-16 17:18:08,972: INFO/Worker-2] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:08,965: INFO/Worker-2] Exporting to folder [DatumInContext(value=u'5a0dc8270640fd5788708933', path=Fields('id'), context=DatumInContext(value={u'id': u'5a0dc8270640fd5788708933'}, path=Fields('folder'), context=DatumInContext(value={u'folder': {u'id': u'5a0dc8270640fd5788708933'}}, path=Fields('output'), context=DatumInContext(value={u'numberOfGpusPerNode': 0, u'numberOfSlots': 1, u'image_spec': {u'owner': u'695977956746', u'tags': {u'openfoam': u'1612'}}, u'next': {u'chord_size': None, u'task': u'hpccloud.taskflow.openfoam.tutorial.create_openfoam_job', u'args': [], u'options': {}, u'subtask_type': None, u'kwargs': {}, u'immutable': False}, u'queue': u'', u'input': {u'shFile': {u'id': u'5a0dc82a0640fd5788708937'}, u'folder': {u'id': u'5a0dc8270640fd5788708934'}}, u'output': {u'folder': {u'id': u'5a0dc8270640fd5788708933'}}}, path=This(), context=None))))]
> [2017-11-16 17:18:09,005: INFO/Worker-2] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:09,014: WARNING/Worker-2] {"field": "name", "message": "An assetstore with that name already exists.", "type": "validation"}
> [2017-11-16 17:18:09,033: INFO/Worker-2] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:09,045: INFO/Worker-4] Connected (version 2.0, client OpenSSH_6.6.1p1)
> [2017-11-16 17:18:09,048: INFO/Worker-2] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:09,067: INFO/Worker-2] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:09,065: ERROR/Worker-2] Exception raise by task.
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/opt/hpccloud/cumulus/cumulus/taskflow/__init__.py", line 117, in wrapped
>     return func(celery_task, *args, **kwargs)
>   File "/opt/hpccloud/hpccloud/server/taskflows/hpccloud/taskflow/openfoam/tutorial.py", line 201, in upload_output
>     girder_token=task.taskflow.girder_token)
>   File "/opt/hpccloud/cumulus/cumulus/tasks/job.py", line 774, in upload_job_output_to_folder
>     assetstore_id = get_assetstore_id(girder_token, cluster)
>   File "/opt/hpccloud/cumulus/cumulus/transport/files/__init__.py", line 54, in get_assetstore_id
>     check_status(r)
>   File "/opt/hpccloud/cumulus/cumulus/common/__init__.py", line 32, in check_status
>     request.raise_for_status()
>   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 844, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> HTTPError: 400 Client Error: Bad Request for url: http://hydra.kitware.com:8080/api/v1/sftp_assetstores
> [2017-11-16 17:18:09,085: ERROR/MainProcess] Task hpccloud.taskflow.openfoam.tutorial.upload_output[235e1605-2fc8-4216-8e5e-38c52e24b266] raised unexpected: HTTPError(u'400 Client Error: Bad Request for url: http://hydra.kitware.com:8080/api/v1/sftp_assetstores',)
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
>     R = retval = fun(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
>     return self.run(*args, **kwargs)
>   File "/opt/hpccloud/cumulus/cumulus/taskflow/__init__.py", line 117, in wrapped
>     return func(celery_task, *args, **kwargs)
>   File "/opt/hpccloud/hpccloud/server/taskflows/hpccloud/taskflow/openfoam/tutorial.py", line 201, in upload_output
>     girder_token=task.taskflow.girder_token)
>   File "/opt/hpccloud/cumulus/cumulus/tasks/job.py", line 774, in upload_job_output_to_folder
>     assetstore_id = get_assetstore_id(girder_token, cluster)
>   File "/opt/hpccloud/cumulus/cumulus/transport/files/__init__.py", line 54, in get_assetstore_id
>     check_status(r)
>   File "/opt/hpccloud/cumulus/cumulus/common/__init__.py", line 32, in check_status
>     request.raise_for_status()
>   File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 844, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> HTTPError: 400 Client Error: Bad Request for url: http://hydra.kitware.com:8080/api/v1/sftp_assetstores
> [2017-11-16 17:18:09,095: WARNING/Worker-4] /usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
>   self._cipher = factory.new(key, *args, **kwargs)
> [2017-11-16 17:18:09,274: INFO/Worker-4] Authentication (publickey) successful!
> [2017-11-16 17:18:09,447: INFO/Worker-4] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:09,526: INFO/Worker-4] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:09,536: INFO/Worker-4] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:09,551: INFO/Worker-4] Starting new HTTP connection (1): hydra.kitware.com
> [2017-11-16 17:18:09,576: INFO/MainProcess] Task cumulus.tasks.job.upload_job_output[b75a0456-92dc-472f-a6f3-d62a8f6606fb] succeeded in 0.820398997s: None

**Comment by cjh1** [comment]
Ok, I see the issue, interestingly @jourdain ran into the same issue last week. Basically there was some failed cleanup of an old cluster, meaning when we try to create an assert store we get a naming clash. We should make this more robust, for now try doing the following:

```bash
vagrant ssh
mongo girder
db.assetstore.remove({type: 'sftp'})
db.clusters.update({name: '<insert cluster name here>'}, {'$unset': {'assetstoreId': ''}})
```

**Comment by jourdain** [comment]
I had to put it back to make it work. So not sure what was the deal. But yes, I ran into something similar.

**Comment by felixveysseyre** [comment]
@cjh1 Well this is weird as I built my VM from complete scratch. I made sure to delete the files from _VirtualBox_ and empty my trash. I do not get how my new VMs could have be impacted by the old ones.

**Comment by felixveysseyre** [comment]
I tried to delete my previous simulation and the related project.
I recreated a new project and the same exact simulation.
Running this simulation succeed this time.

**Comment by cjh1** [comment]
It seem this is resolved.
