### ISSUE TITLE
Girder does not find hpccloud and pvwproxy plugins when main VM (development) is restarted 

### ISSUE THREAD

**Issue by felixveysseyre** [Kitware/HPCCloud-deploy#112]
Hi,

I am working on a new type of _HPCCloud_ simulation and to test it, I would like _HPCCloud-deploy_ to use my own _HPCCloud_ directory.

To do that, I followed the instructions provided at the bottom of this [file](https://github.com/Kitware/HPCCloud-deploy/blob/master/README.md) and built my main VM using:
`DEVELOPMENT=1 vagrant up`

At the end of the building, my VM is running correctly and the _HPCCloud_ directory used is the mine. Everything is working correctly.

Restarting the VM with the following command, I got several issues in the web console:
`vagrant halt && DEVELOPMENT=1 vagrant up`

The issue is:

> GET http://localhost:8888/api/v1/projects 404 (Not Found)

Looking a _Girder_ logs, it seems that `hpccloud` and `pvwproxy` plugins can not be loaded:

> vagrant@vagrant-ubuntu-trusty-64:~$ cat /home/hpccloud/.girder/logs/error.log 
> [2017-12-08 13:04:14,139] ERROR: Required plugin pvwproxy does not exist.
> [2017-12-08 13:04:14,139] ERROR: Required plugin hpccloud does not exist.

Weirdly, these two plugins seem available in the _Girder_ plugin directory:

> vagrant@vagrant-ubuntu-trusty-64:~$ ls -alsh /opt/hpccloud/girder/plugins/
>    0 lrwxrwxrwx  1 hpccloud hpccloud   38 Dec  8 10:15 hpccloud -> /opt/hpccloud/hpccloud/server/hpccloud
>    0 lrwxrwxrwx  1 hpccloud hpccloud   38 Dec  8 10:15 pvwproxy -> /opt/hpccloud/hpccloud/server/pvwproxy
> ...

These two symbolic links seem correct:

> vagrant@vagrant-ubuntu-trusty-64:~$ ls -alsh /opt/hpccloud/hpccloud/server/
> total 0
> 0 drwxr-xr-x 1 hpccloud 1003 204 Nov 22 13:51 hpccloud
> 0 drwxr-xr-x 1 hpccloud 1003 204 Nov 22 13:51 pvwproxy
> 0 drwxr-xr-x 1 hpccloud 1003 204 Dec  7 16:56 taskflows

Thanks for your help !

**Comment by felixveysseyre** [comment]
@jourdain Do you have any intuition concerning this issue ?

@cjh1 took a look yesterday but without success :(

**Comment by cjh1** [comment]
Hi @felixveysseyre, I now understand what you where trying todo. DEVELOPMENT=1 has to be used when the VM is created ( its not enough to halt the VM and then bring it back up ). So try the following ```vagrant destroy && DEVELOPMENT=1 vagrant up```.

**Comment by felixveysseyre** [comment]
Well, some time I just want to restart the VM without rebuilding it.
For example when I restart my computer.

Did I missed something ?

**Comment by cjh1** [comment]
@felixveysseyre Try #113, this should resolve your issue. When the VM is restart the services don't get restarted, this adds two provisioners to ensure this is done. If this resolves the problem please review the PR and then we can merge it.

**Comment by felixveysseyre** [comment]
@cjh1 I tried your pull request and the issue seems to be fixed !

Thanks !

**Comment by cjh1** [comment]
I think this is now resolved
