### ISSUE TITLE
Celery error when creating main VM

### ISSUE THREAD

**Issue by felixveysseyre** [Kitware/HPCCloud-deploy#114]
Hello,

I tried to recreate the main VM this morning and I got the following error:

> TASK [celery : Start celery service] *******************************************
> task path: /Users/felixveysseyre/.../HPCCloud-deploy/ansible/roles/celery/tasks/main.yml:13
> fatal: [hpccloud-vm]: FAILED! => {"changed": false, "failed": true, "msg": "Traceback (most recent call last):\n  File \"/usr/lib/python2.7/runpy.py\", line 162, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/usr/local/lib/python2.7/dist-packages/celery/__main__.py\", line 18, in <module>\n    main()\n  File \"/usr/local/lib/python2.7/dist-packages/celery/__main__.py\", line 14, in main\n    _main()\n  File \"/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py\", line 326, in main\n    cmd.execute_from_commandline(argv)\n  File \"/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py\", line 488, in execute_from_commandline\n    super(CeleryCommand, self).execute_from_commandline(argv)))\n  File \"/usr/local/lib/python2.7/dist-packages/celery/bin/base.py\", line 279, in execute_from_commandline\n    argv = self.setup_app_from_commandline(argv)\n  File \"/usr/local/lib/python2.7/dist-packages/celery/bin/base.py\", line 481, in setup_app_from_commandline\n    self.app = self.find_app(app)\n  File \"/usr/local/lib/python2.7/dist-packages/celery/bin/base.py\", line 503, in find_app\n    return find_app(app, symbol_by_name=self.symbol_by_name)\n  File \"/usr/local/lib/python2.7/dist-packages/celery/app/utils.py\", line 374, in find_app\n    symbol_by_name=symbol_by_name, imp=imp,\n  File \"/usr/local/lib/python2.7/dist-packages/celery/app/utils.py\", line 358, in find_app\n    sym = imp(app)\n  File \"/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py\", line 101, in import_from_cwd\n    return imp(module, package=package)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/opt/hpccloud/cumulus/cumulus/celery/__init__.py\", line 22, in <module>\n    from celery.datastructures import force_mapping\nImportError: No module named datastructures\nTraceback (most recent call last):\n  File \"/usr/lib/python2.7/runpy.py\", line 162, in _run_module_as_main\n    \"__main__\", fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/usr/local/lib/python2.7/dist-packages/celery/__main__.py\", line 18, in <module>\n    main()\n  File \"/usr/local/lib/python2.7/dist-packages/celery/__main__.py\", line 14, in main\n    _main()\n  File \"/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py\", line 326, in main\n    cmd.execute_from_commandline(argv)\n  File \"/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py\", line 488, in execute_from_commandline\n    super(CeleryCommand, self).execute_from_commandline(argv)))\n  File \"/usr/local/lib/python2.7/dist-packages/celery/bin/base.py\", line 279, in execute_from_commandline\n    argv = self.setup_app_from_commandline(argv)\n  File \"/usr/local/lib/python2.7/dist-packages/celery/bin/base.py\", line 481, in setup_app_from_commandline\n    self.app = self.find_app(app)\n  File \"/usr/local/lib/python2.7/dist-packages/celery/bin/base.py\", line 503, in find_app\n    return find_app(app, symbol_by_name=self.symbol_by_name)\n  File \"/usr/local/lib/python2.7/dist-packages/celery/app/utils.py\", line 374, in find_app\n    symbol_by_name=symbol_by_name, imp=imp,\n  File \"/usr/local/lib/python2.7/dist-packages/celery/app/utils.py\", line 358, in find_app\n    sym = imp(app)\n  File \"/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py\", line 101, in import_from_cwd\n    return imp(module, package=package)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\n  File \"/opt/hpccloud/cumulus/cumulus/celery/__init__.py\", line 22, in <module>\n    from celery.datastructures import force_mapping\nImportError: No module named datastructures\n"}

It seems that we are not able to import the `datastructures` from `celery`.

Thanks !

**Comment by cjh1** [comment]
@felixveysseyre Can you run the following inside the failing vm and paste the result, thanks.

```
python
import celery
celery.__version__
```

**Comment by felixveysseyre** [comment]
@cjh1 

Here is what I got:
```
vagrant@vagrant-ubuntu-trusty-64:~$ python
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import celery
>>> celery.__version__
u'4.1.0'
```

**Comment by cjh1** [comment]
That is what I suspected, you are getting the wrong version of celery. Looks like girder upstream have made some changes that is now pulling in that version. I will work out how to fix this up.

**Comment by felixveysseyre** [comment]
Thanks @cjh1 !

I look forward to your fix

**Comment by cjh1** [comment]
@felixveysseyre #115 should resolve this, please test it out.

**Comment by felixveysseyre** [comment]
Your pull request seems to have fixed the issue with Celery.

Thanks @cjh1 !
